### ISSUE TITLE
Guice-related error on Gradle 2.4

### ISSUE THREAD

**Issue by brentvukmer** [jacobono/gradle-jaxb-plugin#36]
Error on `./gradlew clean build:`

```
15:36:01.270 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.jacobo.plugins.JaxbPlugin.class$(JaxbPlugin.groovy)
15:36:01.270 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.jacobo.plugins.JaxbPlugin.$get$$class$com$google$inject$Guice(JaxbPlugin.groovy)
15:36:01.270 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.jacobo.plugins.JaxbPlugin.apply(JaxbPlugin.groovy:51)
15:36:01.270 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.jacobo.plugins.JaxbPlugin.apply(JaxbPlugin.groovy)
15:36:01.270 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
15:36:01.270 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:43)
```

Build.gradle:

```
    compile group: 'org.glassfish.jersey.containers', name: 'jersey-container-servlet-core', version: '2.15'
    compile group: 'org.glassfish.jersey.containers', name: 'jersey-container-servlet', version: '2.15'
    compile group: 'javax.ws.rs', name: 'javax.ws.rs-api', version: '2.0.1'
    compile group: 'org.glassfish.jersey.media', name: 'jersey-media-moxy', version: '2.15'
    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.2'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.2'
    compile group: 'org.jvnet.jaxb2_commons', name: 'jaxb2-basics-runtime', version: '0.9.0'
    compile group: 'com.sun.xml.bind', name: 'jaxb-core', version: '2.2.11'
    compile group: 'com.sun.xml.bind', name: 'jaxb-xjc', version: '2.2.11'
    compile group: 'com.sun.xml.bind', name: 'jaxb-impl', version: '2.2.11'
    compile group: 'javax.xml.bind', name: 'jaxb-api', version: '2.2.12'
    compile group: 'org.jvnet.jaxb2_commons', name: 'jaxb2-basics', version: '0.9.2'
    jaxb 'com.sun.xml.bind:jaxb-core:2.2.11'
    jaxb 'com.sun.xml.bind:jaxb-xjc:2.2.11'
    jaxb "org.jvnet.jaxb2_commons:jaxb2-basics-ant:0.6.5"
    jaxb "org.jvnet.jaxb2_commons:jaxb2-basics:0.9.2"
    jaxb "org.jvnet.jaxb2_commons:jaxb2-basics-annotate:0.6.4"
}


def generatedResources = "src/main/java"

jaxb {
    xsdDir = "src/main/xsd"
    bindingsDir = "src/main/xsd"
    bindings = ["bindings.xjb"]
    episodesDir = "build/generated-resources/main/java"
    xjc {
        destinationDir = generatedResources
        producesDir = generatedResources
        taskClassname = "org.jvnet.jaxb2_commons.xjc.XJC2Task"
    }
}

buildscript {
    repositories {
        maven {
            url "INTERNAL_NEXUS_URL"
        }
    }
    dependencies {
        classpath "org.akhikhl.gretty:gretty:1.2.2"
    }
}

apply plugin: 'org.akhikhl.gretty'

gretty {
    port = 8080
    contextPath = '/jaxb-test'
    servletContainer = 'tomcat8'
    debugPort = 5005      // default
    debugSuspend = true   // default
}
```

**Comment by brentvukmer** [comment]
Reverting to 1.3.5 works fine.

**Comment by scubacabra** [comment]
That's odd -- I didn't change any of that for 1.3.6....

I wonder what could be the problem -- I don't think I use 2.4, but I'll try and give that a shot and see what the problem is.

**Comment by brentvukmer** [comment]
Thanks.  The weird thing is, the sample project we did to evaluate your plugin was using 2.4 and worked fine, several weeks (months?) ago.

**Comment by scubacabra** [comment]
That is strange indeed -- if it was before March 30th then you would have evaluated with 1.3.5. Maybe?

I'll try to run with Gradle 2.4 on the example folder and see what I get -- I'll let you know later tonight.

**Comment by scubacabra** [comment]
I installed 2.4 -- ran the examples folder with it.  Aside from a typo in the `examples/build.gradle` everything runs fine -- no Guice errors.

I know you ran with `gradlew` -- running with `gradle` shouldn't make a difference.

Maybe you can try running with the gradle executable anyways?

I can't replicate it so I'm not sure.. :frowning:

**Comment by brentvukmer** [comment]
Thanks for trying it out!  I'll give it a shot using gradle directly.

**Comment by brentvukmer** [comment]
No love.   FWIW:

```
$ gradle -v

------------------------------------------------------------
Gradle 2.4
------------------------------------------------------------

Build time:   2015-05-05 08:09:24 UTC
Build number: none
Revision:     5c9c3bc20ca1c281ac7972643f1e2d190f2c943c

Groovy:       2.3.10
Ant:          Apache Ant(TM) version 1.9.4 compiled on April 29 2014
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Mac OS X 10.10.3 x86_64

```

**Comment by brentvukmer** [comment]
One important thing to note is that for my work, we access Maven Central via an internal Nexus instance.  It doesn't proxy to JCenter.

**Comment by brentvukmer** [comment]
Got it to work by explicitly adding the guice and gradle-xsd-wsdl-slurping dependencies:

```
buildscript {
    repositories {
        mavenLocal()
        maven {
            url '$internalNexus'
        }
    }
    dependencies {
        classpath 'io.spring.gradle:dependency-management-plugin:0.5.0.RELEASE'
        classpath 'com.google.inject:guice:3.0'
        classpath 'com.github.jacobono:gradle-xsd-wsdl-slurping:1.1.2'
        classpath 'com.github.jacobono:gradle-jaxb-plugin:1.3.6'
        classpath 'com.sun.xml.bind:jaxb-ri:2.2.11'
    }
}
```

**Comment by scubacabra** [comment]
Sweet!

I was driving just now and thinking about it and wondering whether that dependency was getting picked up at all.

You beat me to it! :+1:

**Comment by brentvukmer** [comment]
@jacobono I realize this is closed, but I got a follow-on error until I added:
`classpath 'com.google.inject.extensions:guice-assistedinject:3.0'`

Shouldn't the plugin bundle the guice and guice-assistedinject JARs?

**Comment by scubacabra** [comment]
assistedinject comes from the common jar the two plugins depend on.

https://github.com/jacobono/gradle-xsd-wsdl-slurping/blob/master/build.gradle#L24

I'm guessing the internal nexus repo you have isn't recursively getting all dependencies, like it did for the `gradle-xsd-wsdl-slurping` dependency as well.
