### ISSUE TITLE
Unable to apply plugin

### ISSUE THREAD

**Issue by ghost** [jacobono/gradle-jaxb-plugin#41]
Hello,

I'm trying to use the plugin in my Gradle 2.8 project, but I get the following error:

```
Failed to apply plugin [id 'com.github.jacobono.jaxb']
  No such property: extensions for class: java.lang.String

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':projectname'.
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
    at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
    at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:153)
    at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
    at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
    at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
    at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:499)
    at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
    at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:47)
    at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
    at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
    at org.gradle.internal.Factories$1.create(Factories.java:22)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
    at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
    at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
    at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
    at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    at org.gradle.util.Swapper.swap(Swapper.java:38)
    at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
    at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
    at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.plugins.PluginApplicationException: Failed to apply plugin [id 'com.github.jacobono.jaxb']
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:160)
    at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:112)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:35)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:79)
    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:135)
    at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
    at org.gradle.api.plugins.PluginAware$apply.call(Unknown Source)
    at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
    at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
    at build_9a1g6pkbxdew2m120k8e1qpmb.run(/home/robert/develop/repository/nts/trost-connector/build.gradle:1)
    at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
    ... 58 more
Caused by: groovy.lang.MissingPropertyException: No such property: extensions for class: java.lang.String
    at org.gradle.jacobo.plugins.JaxbPlugin.configureJaxbExtension(JaxbPlugin.groovy:73)
    at org.gradle.jacobo.plugins.JaxbPlugin.this$2$configureJaxbExtension(JaxbPlugin.groovy)
    at org.gradle.jacobo.plugins.JaxbPlugin.apply(JaxbPlugin.groovy:52)
    at org.gradle.jacobo.plugins.JaxbPlugin.apply(JaxbPlugin.groovy)
    at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
    at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:44)
    at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
    ... 69 more
```

Here is my build.gradle:

```
apply plugin: 'com.github.jacobono.jaxb'

dependencies {
    jaxb 'com.sun.xml.bind:jaxb-xjc:2.2.7-b41'
    jaxb 'com.sun.xml.bind:jaxb-impl:2.2.7-b41'
    jaxb 'javax.xml.bind:jaxb-api:2.2.7'
}

jaxb {
   xjc {
     xsdDir = "src/main/resources/"
     generatePackage = "test" 
   }
}
```

Does this have something to do with Gradle 2.8? Or am I doing something wrong here?

**Comment by mangan77** [comment]
Does it work with Gradle 2.7?

**Comment by ghost** [comment]
I just tried it and I get the same error.

**Comment by ghost** [comment]
I also tried 2.1 now (which is mentioned in the readme) but I also get the same error here.

**Comment by scubacabra** [comment]
I don't really use gradle any more, but I just ran the `examples` in this repository and it worked.

I had `2.6` and downloaded `2.8` and they both work.

I can't tell from the output what your problem is exactly, but I would look at the examples for directory for guidance.

^^ just double checked your file and 

``` groovy
jaxb {
   xjc {
     xsdDir = "src/main/resources/"
     generatePackage = "test" 
   }
}
```

should be 

``` groovy
jaxb {
    xsdDir = "src/main/resources/"
   xjc {
     generatePackage = "test" 
   }
}
```

Double check the readme to be sure, but I think that is wrong.

**Comment by ghost** [comment]
Thanks for you answer, but this doesn't change anything unfortunately :/
I looked into the groovy file JaxbPlugin.groovy here at github and found the line that the stacktrace is refering to: 

```
def xjcExtension = project.jaxb.extensions.create("xjc", XjcExtension)
```

It seems that the object "project.jaxb" does not have a child object called "extensions", at least thats how I understand the stacktrace message. But how can that be the case?

**Comment by scubacabra** [comment]
I don't think that is what the stack is saying.  `project.jaxb` is created a few lines before that.

I literally just downloaded gradle `2.8` to double check for you and the examples work.

It's kind of hard to help from a stacktrace without seeing the rest of your setup -- can you clone this repo and run `gradle xjc` in the examples folder?

It works for me -- and if it works for you, you will know it is something wrong with how things are set up in your personal project.

**Comment by ghost** [comment]
I managed to pinpoint the issue to a line from the root build.gradle file:

apply from: "${rootProject.rootDir}/dependencies.gradle"

The project where I want to use your plugin is part of a multi-project-setup, and in the main build.gradle this line is included. The file "dependencies.gradle" contains a "project.ext" declaration, and my guess is that your plugin somehow has problems with this "project.ext" thingy.

**Comment by scubacabra** [comment]
Glad you found it.

If my memory serves me right `project.ext` is a Gradle extensions thing.  You probably should qualify yours for something more specific.  This plugin uses `project.jaxb.ext`

**Comment by ghost** [comment]
You said "You probably should qualify yours for something more specific" - what do you mean by that? How can I solve this now?

**Comment by scubacabra** [comment]
try making it anything but `project.ext`...

`project.gorilla.ext` i don't know.  

If it really isn't an extension on anything, don't name it that. 

YMMV I would check the gradle docs as I can't see that file.

Also take this with a grain of salt.  I haven't used gradle in a while, maybe i'm entirely wrong. Just offering some thoughts without actually seeing the file.

**Comment by ghost** [comment]
project.ext is a gradle feature that allows you to define extra properties that an be used in the whole project. We use this to define common dependencies and their versions in on place. You actually cannot simply "rename" this to "project.bla.ext", it will not work anymore then. You said "This plugin uses project.jaxb.ext" - what exactly is this?

**Comment by scubacabra** [comment]
it sets up a plugin extension called project.jaxb.extensions.  that's how
you can define jaxb { ... xjc { } } properties and make them work
dynamically for your project.

If the project.ext is blocking you, I probably can't be of much help
debugging it (not familiar with it).

I would try and take it out if you can -- otherwise you would have to find
another workaround.
